options:
  amountDummies: 1 # How many dummies can be spawned at the same time. 
  kickDummyAfterSeconds: 600 # A timer to kick a dummy after the amount of time. Set to 0 to disable timer kick
  isAdmin: false # On spawning, a dummy will be an admin
  canExecuteCommands: true # Enabling this a dummy can execute commands without admin or permission.

events:
  allowDamage: true # Enabling this dummy can be damaged.
  callOnCheckValidWithExplanation: true # Before entering the server will be called event Provider.OnCheckValidWithExplanation